"""remove type

Revision ID: 9246f3539e80
Revises: ac21b859ec43
Create Date: 2025-03-12 12:51:55.277705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9246f3539e80'
down_revision = 'ac21b859ec43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
